# deploy-lambda-terraform/.github/workflows/deploy.yml
name: 'Deploy Lambda'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::541356534908:role/GithubActionRole
          aws-region: us-east-1

      - name: Cleanup existing resources
        continue-on-error: true
        run: |
          # Delete Lambda function
          aws lambda delete-function --function-name deploy-lambda-terraform_function || true
          
          # Remove role policies
          aws iam delete-role-policy --role-name deploy-lambda-terraform_lambda_role --policy-name deploy-lambda-terraform_s3_policy || true
          aws iam detach-role-policy --role-name deploy-lambda-terraform_lambda_role --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole || true
          
          # Delete IAM role
          aws iam delete-role --role-name deploy-lambda-terraform_lambda_role || true
          
          # Wait a few seconds for AWS to complete deletions
          sleep 10

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Install Dependencies
        run: |
          cd src
          npm install
          cd ..

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve